### ISSUE TITLE
Unzipping large file with version 1.7 causes UZKErrorCodeBadZipFile error

### ISSUE THREAD

**Issue by brendand** [abbeycode/UnzipKit#30] opened 2016-02-19 08:07 UTC
The large file I sent you before fails to unzip properly about 3/4 of the way through and spews out a bunch of -103 errors (UZKErrorCodeBadZipFile). It doesn't abort the unzipping when it encounters the error. Using my forked version which doesn't contain your latest update works properly for me. I tested this on iOS and Mac. At first I thought it was just on the iOS version but then realized the Mac version also has the problem. So I reverted back to using my framework builds instead of the cocoapod builds.

**Comment by abbeycode** [comment] 2016-02-19 15:54
Hey, sorry about that! It must be a different issue than the last time, since I still have a test case that reproduced the last issue, and it's passing in the latest builds. I'll take a look at this ASAP, but for now, you can still use CocoaPods and stay on the old version:

```
pod 'UnzipKit', '~> 1.6.2'
```

I'll try to figure out what's causing this latest issue ASAP and get back to you.

**Comment by abbeycode** [comment] 2016-02-19 16:30
I was able to successfully extract the archive in a Mac unit test, with no issues. Extracting it using an iOS test case will be more difficult due to its size. I'll see what I can do. You said that you did see the issue with the Mac build also, though?

**Comment by abbeycode** [comment] 2016-02-19 16:35
Also, which commit is your fork up to, and does it have any other changes?

**Comment by brendand** [comment] 2016-02-19 19:21
My latest commit is: d13486ecd555909a6548c600ab021e4efbdd8dde and all my changes were made after your commit c19c4f5c06659705a744dd4252a2f85ef90269b7

You can see my fork here: https://github.com/brendand/UnzipKit

I haven't made any changes to it in 7 days when I removed that new error code I had made. I seem to remember you making a small change to optimize the closing of the file handle.

**Comment by brendand** [comment] 2016-02-19 19:21
And yes, I did get the same failure on the Mac version as well as the iOS version.

**Comment by abbeycode** [comment] 2016-02-19 20:26
Can you please add the following test case into ExtractFilesTests.m (substituting the correct file path) and let me know if it fails? It's succeeding for me.

```ObjC
- (void)testExtractTF_Susan
{
    UZKArchive *archive = [[UZKArchive alloc] initWithURL:[NSURL fileURLWithPath:@"/Users/____/Downloads/TF-Susan’s MacBook Pro-2016-01-07T09-58-39.zip"] error:nil];
    
    NSString *extractDirectory = [self randomDirectoryWithPrefix:@"TF_Susan"];
    NSURL *extractURL = [self.tempDirectory URLByAppendingPathComponent:extractDirectory];
    
    NSError *error = nil;
    BOOL success = [archive extractFilesTo:extractURL.path
                                 overwrite:NO
                                  progress:^(UZKFileInfo *currentFile, CGFloat percentArchiveDecompressed) {
#if DEBUG
                                      NSLog(@"Extracting %@: %f%% complete", currentFile.filename, percentArchiveDecompressed * 100);
#endif
                                  }
                                     error:&error];
    
    XCTAssertTrue(success, @"TF Susan archive failed");
}
```

**Comment by abbeycode** [comment] 2016-02-29 15:51
@brendand Were you able to give that a shot?

**Comment by brendand** [comment] 2016-03-03 16:55
Sorry, I haven't had an opportunity to test it out just yet. I'll be able to look into it next week. The version that I built prior to the last set of changes is working well for me though.

**Comment by abbeycode** [comment] 2016-03-24 21:26
@brendand Should I close the issue, or are you still having this problem?

**Comment by brendand** [comment] 2016-03-25 22:32
Ya, I'm very sorry for not getting back to this. Since the build I have has been working fine for me, I haven't dug into this yet. But when I do get back to it, this can always be re-opened. Just been super busy with other areas of my apps. So close it for now.

**Comment by abbeycode** [comment] 2016-03-25 22:37
Sure, we can work on it more when you have time.

**Closed by abbeycode** 2016-03-25 22:37 UTC
