### ISSUE TITLE
Creating Directory

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#54] opened 2017-04-19 13:20 UTC
Hi,
I couldn't figure out how I can create an empty directory
Thanks

**Comment by amosavian** [comment] 2017-04-19 15:04
resolved by appeding slash to path.

**Comment by abbeycode** [comment] 2017-10-07 20:31
@amosavian I'm going through open issues now, so you'll see me replying to a bunch of them. Sorry to hit you all at once :)

What's the status of this? You closed it, but then reopened it soon thereafter without any comment. Is this still a problem?

**Comment by amosavian** [comment] 2017-10-07 20:53
Sorry I forgot to close it. I made a PR with a function to create a directory inside zip as I remember to address this issue.

**Comment by abbeycode** [comment] 2017-10-07 20:56
You created #57, but I closed it because I thought you asked me to. Should I reopen it?

**Comment by amosavian** [comment] 2017-10-07 21:00
If you wish to have that method in main stream. Personally I implemented it via a swift extension in my code.
Btw, That code is not a solution for this issue.

**Comment by abbeycode** [comment] 2017-10-07 21:04
Could you paste it here for me to see? It's probably generally useful to be able to create empty directories in archives.

**Comment by amosavian** [comment] 2017-10-07 21:18
This is my implementation : https://github.com/abbeycode/UnzipKit/pull/57/files

**Comment by abbeycode** [comment] 2017-10-11 13:09
Yeah, the implementation is straightforward. What's your use case for this?

**Comment by v-vodyanov** [comment] 2017-11-01 16:14
It would be good to have it, cause sometimes you just need to zip some directory with subdirectories and files "as it is", and without empty directories it will be not like that.

By the way, method mirroring "extractFilesTo" would also be awesome :)

**Comment by abbeycode** [comment] 2017-11-06 21:40
@v-vodyanov Would you mind opening an issue for your `extractFilesTo` request, with more detail as to what you would like to see?

**Comment by v-vodyanov** [comment] 2017-11-07 11:50
Sure, here it is - #73

**Comment by abbeycode** [comment] 2019-05-10 00:26
@amosavian was this addressed already (a duplicate of #74)?

**Comment by amosavian** [comment] 2019-05-10 16:46
Yes I did

**Closed** 2019-05-10 20:27 UTC
