### ISSUE TITLE
Empty folders not created during extraction

### ISSUE THREAD

**Issue by denis-ionov** [abbeycode/UnzipKit#74] opened 2017-11-07 12:09 UTC
Steps:
1. Create archive which contains folder with files and empty folder(s)
2. Unzip that archive

Result:
Empty folders does not exist after unpacking

**Comment by abbeycode** [comment] 2017-11-07 12:55
Is this a duplicate of #54 or #55? If not, can you please provide the code you're using to write an empty folder?

**Comment by denis-ionov** [comment] 2017-11-07 13:09
I'm not sure that this is duplicate of [#54](https://github.com/abbeycode/UnzipKit/issues/54) or [#55](https://github.com/abbeycode/UnzipKit/issues/55), because question is about unzip. Empty folders are present in archive, but does not exist after unzip. Maybe this issue is about extracting archive, not creating. If i'm wrong, i can provide some code of creating folder while create archive.

**Comment by abbeycode** [comment] 2017-11-08 12:57
The most helpful thing you could do (likely to result in the swiftest resolution) would be to send a PR with a unit test (or multiple cases) demonstrating the issue. The next best would be to paste those cases into a comment on this issue.

**Comment by amosavian** [comment] 2018-01-10 06:39
I've solved this issue for myself. I can send a PR.

**Comment by abbeycode** [comment] 2018-02-02 02:45
Please send the PR and I'll take a look. Thanks @amosavian!

**Comment by abbeycode** [comment] 2019-05-10 00:24
This has been addressed with pull requests #78 and then #82, both now merged.

**Closed by abbeycode** 2019-05-10 00:24 UTC
Labels: enhancement
