### ISSUE TITLE
Empty directories are duplicated when deleted and added again

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#55] opened 2017-04-19 18:58 UTC
When I delete a file a folder, then add a file with same name, I got duplicated entries with same name.

**Comment by abbeycode** [comment] 2017-04-21 19:40
Thanks for reporting this. Can you please take a look at [the issue template I created](https://github.com/abbeycode/UnzipKit/blob/master/.github/ISSUE_TEMPLATE.MD) and copy/paste into your issue? I could use the additional info requested there to figure out what's going on for you. I'm going to paste this into Issue #56 also.

**Comment by amosavian** [comment] 2017-04-22 08:32
**Steps to reproduce:**
1- Add a file to zip with `writeData:filePath:progress:error:`
2- Delete file using `deleteFile:error:`
3- Readd file using step 1
4- List files using `listFileInfo:`
Result of step 4 contains file 2 times.

**Comment by abbeycode** [comment] 2017-04-24 18:55
I've pushed a test case into a branch that follows the code you described, but with correct results. Can you please update the test case so it fails in the way you're expecting?

**Comment by amosavian** [comment] 2017-04-24 18:59
Weird because I got it fixed now!

**Comment by amosavian** [comment] 2017-04-25 07:39
Finally I found the problem. 
1- create an empty folder, not file, using the code I made a pull request.
2- delete that folder
3- create an empty folder with same name again

I think the problem occurs when data is empty, instance of `[NSData data]`.

**Comment by abbeycode** [comment] 2017-08-08 18:06
Is this something you're still working on?

**Comment by abbeycode** [comment] 2017-10-07 20:34
@amosavian I'm going through open issues now, so you'll see me replying to a bunch of them. Sorry to hit you all at once :)

Are you still taking a look at this, or should I close it out?

**Comment by amosavian** [comment] 2017-10-07 20:55
This problem still exists. This only occurs when I create folder in zip, not a regular file.

**Comment by abbeycode** [comment] 2017-10-07 21:02
So steps to reproduce are the following?

1. In an archive add an empty directory (use `[NSData data]`)
2. Delete the directory created
3. Create that directory again

And then what happens at that point? Is an `NSError` returned?

**Comment by amosavian** [comment] 2017-10-07 21:11
No, when I list archive files at then end, I get entry twice. Indeed deleted directory revives somehow.

**Comment by abbeycode** [comment] 2017-10-11 12:53
I created a test case again (this time it happens to be in Swift because the file with other `writeData` tests is in Swift. The test case is passing for me. Can you take a look again and see if we can modify it so it demonstrates your issue?

**Comment by abbeycode** [comment] 2017-10-20 20:59
@amosavian Have you had a chance to look at the test case I set up?

**Comment by amosavian** [comment] 2017-10-21 15:17
I did

**Comment by abbeycode** [comment] 2017-10-22 19:22
I pushed an update with the trailing slash, and the case still passes

**Comment by abbeycode** [comment] 2019-07-02 12:11
I just updated the `emptydir` branch so the test case I wrote is on the latest v2.0 branch. Do you have any time to modify that test case to reproduce your issue in a PR?

**Comment by abbeycode** [comment] 2019-08-01 12:39
@amosavian I'm going to close this, since I haven't heard back from you in a while. Please feel free to reopen if you'd like to work with me on this at some point.

**Closed by abbeycode** 2019-08-01 12:39 UTC
Labels: bug
