### ISSUE TITLE
UZKArchive doesn't support password?

### ISSUE THREAD

**Issue by iblacksun** [abbeycode/UnzipKit#12] opened 2015-06-16 07:33 UTC
1. Call `UZKArchive.zipArchiveAtPath(zipFilePath, password: "111111")` to create a zip file
2. Call `zipArchive.writeData(data, filePath: file, error: &error)` to write data to zip file

The file is created successfully, but when I unzip the file use iZip, it prompts that the password cannot unzip with "111111".

**Comment by abbeycode** [comment] 2015-06-16 13:44
Based on the code you gave, it looks like you're using Swift. Is that correct?

**Comment by iblacksun** [comment] 2015-06-16 15:11
@abbeycode You are right.

**Comment by abbeycode** [comment] 2015-06-16 15:13
I'm taking a look - so far, I confirmed that a file written with `111111` as the password opens using BetterZip (I don't have iZip). I'm writing a test case in Swift now to see if that's possibly what's causing the bug. I'll let you know.

**Comment by abbeycode** [comment] 2015-06-16 18:45
I created a branch, [Issue12](https://github.com/abbeycode/UnzipKit/tree/issue12), with new Swift and Obj-C test methods named `testWriteData_PasswordProtected`. Even though the files extract successfully using BetterZip for me, I was able to verify they don't extract using the `unzip` command line tool (and it doesn't seem like Swift is a factory, though I wrote the test cases in both languages). Thanks for pointing this out, and I'll see if I can figure out what's going wrong.

**Comment by abbeycode** [comment] 2015-06-17 13:53
I see a bunch of different apps named "iZip" - could you provide a link to the one you use?

**Comment by iblacksun** [comment] 2015-06-18 01:52
@abbeycode Here is it. https://itunes.apple.com/us/app/izip-zip-unzip-tools-for-archive/id412758079?mt=12&ign-mpt=uo%3D4

**Comment by abbeycode** [comment] 2015-06-18 16:06
Thanks. I had sent an email to the wrong iZip at first, and am unable to use T-Bone's contact form (the CAPTCHA is broken), but I was also able to reproduce the failure with WinZip for Mac and PC, so hopefully they can help point me in the right direction.

**Comment by abbeycode** [comment] 2015-06-22 16:34
This has been merged into master, and will be included in v1.4 of UnzipKit. Thanks for pointing this out! I'll send a final update once 1.4 is pushed to CocoaPods.

**Comment by abbeycode** [comment] 2015-06-22 16:45
This is live on CocoaPods now

**Closed by abbeycode** 2015-06-22 16:45 UTC
Labels: bug
